### PR TITLE
NOJIRA: Updating links, using https where possible.

### PR DESCRIPTION
**Pull request by jobara**

### CODE REVIEW

**Comment by michelled** [comment]
There is a link to the TextfieldSlider tests that has the wrong path. 
I also got 'unable to connect' when I tried to load the metadata demos - should I expect that?

**Comment by jobara** [comment]
@michelled I wasn't able to reproduce the issue you had with the metadata demos using FF. I have found that in Safari if you click through the link normally it works, but if you use the context menu or keyboard shortcut to open them in a new page it doesn't. This is because it tries to go to use https, but those pages only support http currently. I haven't seen this anywhere other than Safari though, and talked to Gio about it yesterday. He's planning on moving all of the sites over to https eventually.

**Comment by gtirloni** [comment]
The HTTPS work can be tracked here: https://issues.fluidproject.org/browse/INFRA-86

**Comment by jobara** [comment]
@michelled I've updated the links to the metadata demo to use https.

**Pull request merged**
